---
title: "DAG"
author: "Brian Holt"
date: "5/6/2020"
output:
  html_document: null
  pdf_document: default
  toc: yes
  toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(tidyverse)
library(here)
library(ggdag)
library(dagitty)
```


```{r}
dag <- dagitty("dag {
  X1 -> X2
  X1 -> Y
  X3 -> X2
  X2 -> Y
  X2 -> T -> Y
  X3 -> T
               }")
plot( graphLayout( dag ) )
```

```{r}
smoking_ca_dag <- dagify(cardiacarrest ~ cholesterol,
       cholesterol ~ smoking + weight,
       smoking ~ unhealthy,
       weight ~ unhealthy,
       labels = c("cardiacarrest" = "Cardiac\n Arrest", 
                  "smoking" = "Smoking",
                  "cholesterol" = "Cholesterol",
                  "unhealthy" = "Unhealthy\n Lifestyle",
                  "weight" = "Weight"),
       latent = "unhealthy",
       exposure = "smoking",
       outcome = "cardiacarrest")

ggdag(smoking_ca_dag, text = FALSE, use_labels = "label")
```




```{r}

layout <- data.frame('x'=seq(1:2),'y'=seq(1,2),
                     'name'= c('family.meals','eatingdis'))
eating_dis_dag <- dagify(eatingdis ~ family.meals,
       labels = c("eatingdis" = 'eating disorder', 
                  "family.meals" = "Family meals"),
       exposure = "family.meals",
       outcome = "eatingdis",
       coords = layout )

ggdag_dseparated(from='family.meals', to='eatingdis', eating_dis_dag, text = FALSE, use_labels = "label")
```

```{r}
dagify(fever ~ flu + pox, 
        acetaminophen ~ fever,
        labels = c("flu" = "Influenza",
                   "pox" = "Chicken Pox",
                   "fever" = "Fever",
                   "acetaminophen" = "Acetaminophen")) %>% 
ggdag_dseparated(from = "flu", to = "pox", controlling_for = "acetaminophen",
                 text = FALSE, use_labels = "label")
```


```{r}
layout <- as.data.frame(matrix(c(seq(1:4), seq(1:4)), ncol = 2))

layout$name <- c("flu", "pox", "fever", "acetaminophen")

colnames(layout)[1:2] <- c("x", "y")

dagify(fever ~ flu + pox,

acetaminophen ~ fever,

labels = c("flu" = "Influenza",

"pox" = "Chicken Pox",

"fever" = "Fever",

"acetaminophen" = "Acetaminophen"),

coords = layout) %>%

ggdag_dseparated(from = "flu", to = "pox", controlling_for = "acetaminophen",

text = FALSE, use_labels = "label")
```



```{r,bayescorona}

layout <- list(x=c(begin_100=1,
                   Virus_0.4=2,
                   NoVirus_99.6=2,
                   TruePos_97=3,
                   FalseNeg=3,
                   FalsePos_3=3,
                   TrueNeg=3),
               y=c(begin_100=0,
                   Virus_0.4=1,
                   NoVirus_99.6=-1,
                   TruePos_97=2,
                   FalseNeg=1,
                   FalsePos_3=-1,
                   TrueNeg=-2)
               )

layout
BayesCorona <- dagify(
  Virus_0.4~begin_100,
  NoVirus_99.6~begin_100,
  TruePos_97~Virus_0.4,
  FalseNeg~Virus_0.4,
  FalsePos_3~NoVirus_99.6,
  TrueNeg~NoVirus_99.6,
  coords=layout
)
ggdag( BayesCorona ,node_size = 35)
```




# for Buelah

```{r}
chae <- dagitty("dag {
  Exposure_to_alc -> Want_to_copy_parents_bx
  Want_to_copy_parents_bx -> Alcohol_abuse
  Toxic_home_enviornment -> Exposure_to_alc
  Toxic_home_enviornment -> child_wants_sense_of_belong
  child_wants_sense_of_belong -> Want_to_copy_parents_bx
               }")
plot( graphLayout( chae ) )
```